In [1]:
#Aim : To create 1D , 2D and Multidiamensional array

In [2]:
#Name: Gauri Tarachand Kadu
#Roll no: 26
#Sec: A
#Subject: ET-1
#Date:19/08/2025

In [3]:
#importing the basic library
import numpy as np

In [4]:
#creating 1D array using numpy

In [5]:
a1=np.array([10,20,30,40,50])

In [6]:
a1

array([10, 20, 30, 40, 50])

In [7]:
a2=np.array([[10,20,30,40],[60,70,80,90]])

In [8]:
a2

array([[10, 20, 30, 40],
       [60, 70, 80, 90]])

In [9]:
#creating 2D array using matrix

In [10]:
a3=np.matrix('11 22;33 44;55 66')
print(a3)

[[11 22]
 [33 44]
 [55 66]]
